# Generated by Django 3.2.6 on 2023-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station_00000235',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('air_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dew_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station_002099C5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('air_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station_0020CF3B',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('air_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
