# Generated by Django 3.2.7 on 2022-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('air_temp_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('relative_humidity_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_temp_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
