# Generated by Django 3.2.6 on 2023-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_station_gallipoli_station_jena'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('station_id', models.TextField()),
            ],
        ),
    ]
