# Generated by Django 3.2.6 on 2023-11-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station_Gallipoli',
        ),
        migrations.DeleteModel(
            name='Station_Jena',
        ),
    ]
