# Generated by Django 3.2.7 on 2022-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220128_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_002099C5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('air_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Station_0020B06B',
        ),
    ]
