# Generated by Django 3.2.7 on 2022-01-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220128_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_002099c5',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='station_0020cf3b',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
