# Generated by Django 3.2.6 on 2023-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20231128_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_Gallipoli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sunshine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_rad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mean_sea_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station_Jena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('T', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Tpot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Tdew', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VPmax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VPact', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VPdef', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('H2OC', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_wv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
