# Generated by Django 3.2.6 on 2023-11-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_station_gallipoli_station_jena'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station_Gallipoli',
        ),
        migrations.DeleteModel(
            name='Station_Jena',
        ),
    ]
