# Generated by Django 3.2.7 on 2022-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220128_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_002099c5',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station_0020cf3b',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
