# Generated by Django 3.2.7 on 2022-01-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220130_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station_002099c5',
            old_name='id',
            new_name='name_id',
        ),
        migrations.RenameField(
            model_name='station_0020cf3b',
            old_name='id',
            new_name='name_id',
        ),
    ]
