# Generated by Django 3.2.7 on 2022-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220130_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_00000235',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(null=True)),
                ('air_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dew_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
