# Generated by Django 3.2.6 on 2023-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_user_models_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_models',
            name='station_id',
            field=models.TextField(),
        ),
    ]
