# Generated by Django 3.2.6 on 2023-12-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_user_models_station_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Models',
        ),
    ]
