# Generated by Django 3.2.6 on 2023-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_delete_user_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('station_info', models.JSONField()),
            ],
        ),
    ]
